media:
  input: src/media
  output: /media
content:
  - name: docs
    label: Documentation
    type: collection
    path: src/docs
    filename: "{primary}.md"
  - label: Home page
    path: src/index.njk
    name: homepage
    type: file
    
  