media:
  input: assets
  output: /media
images:
  input: assets/images
  output: /media/images
content:
  - name: pages
    label: Pages
    type: collection
    path: src/pages
    filename: "{primary}.md"
  - label: Home page
    path: src/index.njk
    name: homepage
    type: file
    
  