media:
  input: src/media
  output: /media
content:
  - name: pages
    label: Pages
    type: collection
    path: src/pages
    filename: "{primary}.md"
  - label: Home page
    path: src/index.njk
    name: homepage
    type: file
    
  