media:
  - name: files
    label: Files
    input: assets/files
    output: /media/files
    categories: [ document ]
  - name: images
    label: Images
    input: assets/images
    output: /media/images
    extensions: [ jpg, png, webp ]
content:
  - label: Home Page
    path: pages/home.md
    name: homepage
    type: file
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }, required: true}
      - { name: body, label: Body, type: rich-text, hidden: true }
      - { name: meta_description, label: Meta Description, type: string, options: { maxlength: 180 }}
      - { name: meta_title, label: Meta Title, type: string, options: { maxlength: 120 }}
      - { name: subscribe, label: Subscribe, type: boolean, default: false, hidden: true }
    
  - name: pages
    label: Main Pages
    type: collection
    path: pages
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
      
  - name: posts
    label: Posts
    type: collection
    path: collections/_posts
    view: 
      fields: [ title, published, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - { name: comments, label: Comments, type: boolean, default: false, hidden: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 }}
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }

  - name: projects
    label: Projects
    type: collection
    path: collections/_projects
    view: 
      fields: [ title, published, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - { name: description, label: Description, type: string, options: { maxlength: 160 }}
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }
  