media:
  input: assets
  output: /media
content:
  - label: Home Page
    path: pages/home.md
    name: homepage
    type: file
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }, required: true}
      - { name: body, label: Body, type: rich-text }
      - { name: meta_description, label: Meta Description, type: string, options: { maxlength: 180 }}
      - { name: meta_title, label: Meta Title, type: string, options: { maxlength: 120 }}
      - { name: subscribe, label: Subscribe, type: boolean, default: false, hidden: true }
      
  - name: Global
    label: Global Settings
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be used for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
        hidden: true
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
    
  - name: pages
    label: Main Pages
    type: collection
    path: pages
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
      
  - name: posts
    label: Posts
    type: collection
    path: collections/_posts
    view: 
      fields: [ title, published, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - { name: comments, label: Comments, type: boolean, default: false, hidden: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 }}
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }
  