media:
  input: assets
  output: /media
content:
  - name: pages
    label: Pages
    type: collection
    path: pages
    filename: "{primary}.md"
  - label: Home page
    path: pages/home.md
    name: homepage
    type: file
    
  